docker_swarm_watcher: docker-swarm-watcher -u $DOCKER_SWARM_WATCHER_USERNAME -p $DOCKER_SWARM_WATCHER_PASSWORD -c "/app/comsave/after_docker_service_event.sh" -e="service:create,service:remove,service:update"
nginx: nginx
